baseURL = 'https://itszariep.codeberg.page/'
languageCode = 'en-us'
title = "Zariep's portfolio"
theme = "Tessera"

[params]
  author = "ItsZariep"

  [[params.social_links]]
    name = "Codeberg"
    url = "https://codeberg.org/itszariep"

  [[params.social_links]]
    name = "Ko-fi"
    url = "https://ko-fi.com/itszariep"

  [[params.social_links]]
    name = "Youtube"
    url = "https://youtube.com/@itszariep"